### ISSUE TITLE
"File does not exist" for parent path validation in composer.json autoload section.

### ISSUE THREAD

**Issue by nitso** [psliwa/idea-composer-plugin#10]
I've got (not usual) project structure looking like this: 
```
project/
-- deploy/ <project root>
  -- src <project sources>
  -- composer.json
-- tests/ <tests root>
  -- src/ <Utility classes used in tests only>
  -- unit/ <tests sources>
```
So in composer json I've got autoload section looking like this:
```json
"autoload": {
    "psr-4": {
        "Project\\": "src/",
        "ProjectTests\\": "../tests/src"
    }
}
```

And I've got validation error for `../tests/src`: "File does not exist". Editor suggests creating and <!!!> can create directory named double-dots ".." (I'm on a Windows machine). 

Composer's autoload understands well relative parent path in autoload for my project structure.

**Comment by psliwa** [comment]
Thanks for info. The bug will be fixed in next release.

**Comment by nitso** [comment]
Thanks!
