### ISSUE TITLE
Add support for build 141

### ISSUE THREAD

**Issue by acelayawonnova** [psliwa/idea-composer-plugin#11]
Recently PhpStorm 9 was released, which is based on build 141, and this plugin cannot be installed on it.

**Comment by psliwa** [comment]
Thanks, I will check it asap.

**Comment by psliwa** [comment]
Can you provide more informations? There is any error message, backtrace on startup or something like that? Plugin does not show on plugin list? I have installed PhpStorm 9 and I was able to install this plugin and it works ok.

**Comment by acelayawonnova** [comment]
I didn't see it in the list of plugins by searching "composer", and assumed it wasn't compatible, but I'll check again.

**Comment by acelayawonnova** [comment]
I'm sorry, my mistake. I was looking for the plugin in the "Install JetBrains plugins" list, instead of the "Browse repositories" list.
Thanks for your quick answer :-)

**Comment by psliwa** [comment]
No problem ;)
