### ISSUE TITLE
Malfunction when .idea is not in project directory  

### ISSUE THREAD

**Issue by ZdenyC** [psliwa/idea-composer-plugin#13]
When creating new project and place project setting with .idea in different directory, excluded from project and add new root directory for project files, then autocomplete of template is not working.

**Comment by psliwa** [comment]
How can I create a project which `.idea` directory is not in project root directory?

**Comment by ZdenyC** [comment]
Just create a new project anywhere where you want to store your project data, then go to "Settings | Directories" and detach its dir and attach your project root folder.

**Comment by psliwa** [comment]
I cannot reproduce this. I create new project, then go to "Project Structure | Modules" (I have no "Settings | Directories"), on the right side is panel with root directories - I click "x" (remove) on exisiting one, click "Add content root" and choose some different directory, I click "Apply" and "Ok", create new composer.json file and plugin still works ok in this file.

What PhpStorm and JDK version do you have? When you create normal project (without changing project root) plugin works ok?

**Comment by ZdenyC** [comment]
Without changing project root plugin works.
PhpStorm 9.01, same error was in previous versions of PhpStorm

Try create new project "some_project_name" with "Project type" Empty project
Then go to Setting > Project:some_project_name > Directories.
Here exculde current directore and add new Content Root

**Comment by psliwa** [comment]
I cannot reproduce the issue.
