### ISSUE TITLE
Error while compiling CompletionTest.scala

### ISSUE THREAD

**Issue by Maks3w** [psliwa/idea-composer-plugin#19]
While trying to compile the sources I got the following failure.

 > idea-composer-plugin/src/test/scala/org/psliwa/idea/composerJson/intellij/codeAssist/CompletionTest.scala
Error:(35, 5) not found: value assertDoesntContain
    assertDoesntContain(lookupElements, unexpectedSuggestions:_*)
    ^
Error:(13, 25) not found: value assertContainsElements
  ): Unit = suggestions(assertContainsElements(_, _:_*))(contents, expectedSuggestions, unexpectedSuggestions)
                        ^
Error:(19, 25) not found: value assertContainsOrdered
  ): Unit = suggestions(assertContainsOrdered(_, _:_*))(contents, expectedSuggestions, unexpectedSuggestions)
                        ^

Do you know what is missing?

**Comment by psliwa** [comment]
What Intellij version for SDK do you use (Project Structure > Project > Project SDK)? You should use 141.+, because there were changes in testing framework in SDK.

**Comment by Maks3w** [comment]
I've try with 14 CE, 15 CE EAP and 15 EAP

**Comment by psliwa** [comment]
Ok, sorry - I've fixed this problem :) Please try to pull the newest master. I had the same problem few weeks ago, I fixed that but I forgot to push changes to origin.

**Comment by Maks3w** [comment]
Works. I wish to see a CI for this.
