### ISSUE TITLE
Use caret listener for VersionOverlay

### ISSUE THREAD

**Issue by Haehnchen** [psliwa/idea-composer-plugin#21]
Your package version overlay is a nice feature but you implemented it a very tricky way. You should better use a `com.intellij.openapi.editor.event.CaretListener`, see corresponding commit in Symfony Plugin:
https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/b8f59c1db7340395bcaa918fd9dc257ad8db7afc

**Comment by psliwa** [comment]
Thanks for suggestion. I was looking for how to implement this feature and I didn't find better solution. I will try to use `CaretListener`.

**Comment by psliwa** [comment]
`VersionOverlay` has been refactored - code is ~30 lines shorter. https://github.com/psliwa/idea-composer-plugin/commit/594fb951a0101bdd74ccbedb8a700b6f3a6f52e6

**Comment by Haehnchen** [comment]
:thumbsup:
