### ISSUE TITLE
no `path` autocomplete in the `type` key

### ISSUE THREAD

**Issue by lakhman** [psliwa/idea-composer-plugin#22]
Assume we have a composer file like so:

```json
{
    "name": "app",
    "repositories": [
        {
            "type": "path",
            "url": "/Users/username/path/to/local/repo"
        }
    ]
}
```

When I try to autocomplete "path" as the "type" it shows all others but `path` is missing, would be nice if could be added, also if we could actually autocomplete the path also (view a dropdown of the live file system?).

**Comment by lakhman** [comment]
oops, sorry, it should've been called vcs, it does complete!

**Comment by lakhman** [comment]
View the details here:

https://getcomposer.org/doc/05-repositories.md#path

**Comment by psliwa** [comment]
Thanks! I will add a due support for path repository soon :)

**Comment by psliwa** [comment]
I've added "path" to repository types + as a bonus packages from "path" repositories also are available in package and version code completion.

https://github.com/psliwa/idea-composer-plugin/commit/e3194442f3eac97e82eab1d660ea4d6861889090
