### ISSUE TITLE
Can't get autocomplete to work with my private packagist repository

### ISSUE THREAD

**Issue by rrajkomar** [psliwa/idea-composer-plugin#24]
I've set up a local server with a packagist installed on it.Getting dependencies with composer update/install works fine but I can't seem to make the autocomplete work.

**Comment by psliwa** [comment]
Hi, thanks for reporting an issue. When you disable your private repo (i.e. by removing it from "repositories" property), does autocomplete work? What IntelliJ / PhpStorm and java version and OS do you use?

**Comment by rrajkomar** [comment]
When you disable your private repo (i.e. by removing it from "repositories" property), does autocomplete work? 
Yes but only for public packagist packages, not my private ones

What IntelliJ / PhpStorm and java version and OS do you use?
Latest EAP version :

```
PhpStorm PS-144.3891.12
Build #PS-144.3891, built on February 10, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

OpenJDK 8 (8u72) :
```
java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
```
Debian 8 (latest stable version released, currently 8.3) :
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.3 (jessie)
Release:	8.3
Codename:	jessie
```

**Comment by psliwa** [comment]
Ok, I got it. Yes, there is no way right now that custom packagist repository works ok. Only simple repositories like satis work. I will try to fix that soon.

**Comment by rrajkomar** [comment]
Hello,
Are there any updates on this issue ?

**Comment by psliwa** [comment]
I haven't started to work on that yet. Maybe I will start this weekend, but this is rather big task to do, so I wouldn't expect this feature in 2-3 weeks.

**Comment by psliwa** [comment]
In `1.0.13` version it should work.

**Comment by rrajkomar** [comment]
Hi I've updated my plugin to the specified version and I'm still having the issue...

**Comment by SilvanLaroo** [comment]
I also have this issue on 2016.3, if I add a custom url the autocomplete does not work anymore.

**Comment by SilvanLaroo** [comment]
Unfortunately still not working, would be great if we can get this to work.
