### ISSUE TITLE
Plugin marks composer.json contents as errored when there's no 'name' or 'description' properties

### ISSUE THREAD

**Issue by chrisemerson** [psliwa/idea-composer-plugin#28]
I get errors "The 'name' property is required" and "The 'description' property is required" when viewing my composer.json file. However, these properties are only required for published packages, not for projects which are just using composer to manage their dependencies.

See official documentation at: https://getcomposer.org/doc/04-schema.md#name

**Comment by psliwa** [comment]
Yes, you are right. I was sure `name` and `description` are required for all projects (they were some time ago) - I will fix this asap. The output from `composer validate` misguided me. Thanks for watchfulness.

**Comment by chrisemerson** [comment]
Thanks for the quick response :)
