### ISSUE TITLE
Adding menu for composer actions

### ISSUE THREAD

**Issue by IAmJulianAcosta** [psliwa/idea-composer-plugin#29]
It would be nice if this plugin adds a menu like the one used by vagrant, so we can launch operations like composer update without opening terminal

![screen shot 2016-03-07 at 4 13 35 p m](https://cloud.githubusercontent.com/assets/1844640/13583565/166876c8-e480-11e5-94d1-3ee49a1bcd7b.png)

**Comment by psliwa** [comment]
Thanks for suggestion. This kind of menu is provided by PhpStorm / php plugin itself. It is very poor, it has only 2 options (init composer and add dependency). I think this kind of feature should be provided by official plugin (this is not dealing with composer.json file - my plugin is focused only on that), but I will see if there is possibility to add custom menu items to composer menu. If it is possible, I will extend it.

**Comment by psliwa** [comment]
It is possible to add such menu items, but I think it should be included in PhpStorm core rather than this plugin.
