### ISSUE TITLE
"Init composer" is not available before indexing of the project

### ISSUE THREAD

**Issue by stof** [psliwa/idea-composer-plugin#31]
As changing the library paths impacts the indexing, it would make sense to be able to configure it as soon as possible rather than having to wait until PhpStorm indexed all vendors as being project files (which can take some time)

**Comment by psliwa** [comment]
"Init composer" is not a feature of the plugin, it is native PhpStorm feature, so I am not able to change this :(

**Comment by stof** [comment]
oh, I thought it was coming from this plugin.
So closing this
