### ISSUE TITLE
Scipts: Package Events - First parameter type of 'x' is invalid.

### ISSUE THREAD

**Issue by Goon3r** [psliwa/idea-composer-plugin#37]
Hello,

I think there is an issue with the inspections on Package Event scripts.

https://getcomposer.org/doc/articles/scripts.md
The composer documentation dictates that Package Events should recieve an Event subclass of:  Composer\Installer\PackageEvent as a first argument however a warning is produced for these script definitions if a Composer\Script\Event object is not the first parameter.

I imagine this might be the case for all events that recieve a subclass, can we tighten up the script inspections please so that no false warnings are produced.

Thanks

EDIT: sorry for not being able to provided any fixes etc for this

**Comment by psliwa** [comment]
Thanks for reporting an issue 👍  I will take a look at this soon.
