### ISSUE TITLE
Package name completion in requirements does not work once reaching the /

### ISSUE THREAD

**Issue by stof** [psliwa/idea-composer-plugin#38]
when I start typing the package name in the requirement, the completion popup opens. But as starting to type ``symf`` gives me lots of results, I continued typing. Once reaching ``symfony/``, it drops all results instead of listing the Symfony packages. This stays true after typing more chars (I was adding ``symfony/phpunit-bridge`` when trying this)

**Comment by psliwa** [comment]
Thanks, I will fix this soon 👍

**Comment by psliwa** [comment]
Will be fixed in next release. I can see there is an exception thrown by Intellij in such situation, probably bug in the Intellij core. I managed to workaround this.
