### ISSUE TITLE
[Feature request] Automatic PSR-4 and PSR-0 namespace mappings

### ISSUE THREAD

**Issue by Ayesh** [psliwa/idea-composer-plugin#42]
Hi,
Thanks for the awesome plugin. The composer.json schema hints, package search and everything is super awesome!

Is there any plans to make this plugin inspect the `autoload` and `autoload-dev` sections of the composer.json file and add them to the namespace settings automatically (what you would set manually at Settings -> Directories)? It would be a really nice feature to have. 

Thanks again,
Ayesh.

**Comment by acelaya** [comment]
PhpStorm includes this feature itself since v2017.2, so I think this issue can be closed.
