### ISSUE TITLE
When Packagist is not Available Plugin Freezes Whole IDE

### ISSUE THREAD

**Issue by kiler129** [psliwa/idea-composer-plugin#44]
Packagist has it's better and worse moments - sometimes it stops responding from some networks usually in a way the page loads forever and never finishes. The problem is PHPStorm plugin has no support for such situation - if you try to edit `composer.json` file while packagist is not available whole IDE hangs (since plugin tries to load autocompletion information for versions) and never recover.

**Comment by psliwa** [comment]
Thanks, I've fixed the issue in `1.0.21` version.

**Comment by kiler129** [comment]
@psliwa Thanks!

**Comment by 9iks** [comment]
> Thanks, I've fixed the issue in `1.0.21` version.

mac => 10.13.6
PHPStorm => 2019.1
PHP composer.json support => v1.0.27

Input character, program ide no response
