### ISSUE TITLE
Dismiss or disable "This configuration file contains list of Composer dependencies" message

### ISSUE THREAD

**Issue by NiceGuyIT** [psliwa/idea-composer-plugin#47]
Copied from https://youtrack.jetbrains.com/issue/WI-37611.

## What steps will reproduce the problem?
1. Install the "PHP composer.json support" plugin.
2. Open a composer.json file, presumably one that has been configured for a project.
3. A message is displayed at the top, "This configuration file contains list of Composer dependencies", with options to Install and Update.

## What is the expected result?
I expect to be able to get rid of the message in some way, either with a "Dismiss" button, X button like a notification, or through a configuration option.

## What happens instead?
There appears to be no way to disable this dialog. See the comment in this YouTube video (https://www.youtube.com/watch?v=J58z0njPLMg):
> Is there a way to disable the "This configuration file contains list of Composer dependencies" popup in composer.json? I don't like it at all, so I would love to find out a way to disable it. Thanks﻿
Response:
>> There's no such a way. Is it that bad? Feel free to submit a usability issue: https://youtrack.jetbrains.com/newIssue?project=WI﻿

## Environment and versions
- openSUSE Leap 42.2
- PhpStorm 2017.2.1
- Build #PS-172.3544.41, built on August 2, 2017
- JRE: 1.8.0_152-release-915-b6 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Linux 4.4.74-18.20-default
- PHP composer.json support Version: 1.0.21

**Comment by psliwa** [comment]
Hi,

jetbrains support is wrong, this message is not generated by composer.json plugin - Eugene Morozov is wrong. So I am not able to help you.
