### ISSUE TITLE
[Feature request] Do not mark warning on roave/security-advisories package

### ISSUE THREAD

**Issue by acelaya** [psliwa/idea-composer-plugin#48]
The plugin marks a warning on the "require" block if you are not including the roave/security-advisories package, but if you include it, since it can only be installed using the dev-master constraint, another warning is marked on the package itself saying that using dev-master is not a good idea.

I think it makes sense to exclude this specific package from that check, since it is the only way to install it.

Thoughts?

**Comment by rieschl** [comment]
The warning if you don't include the `roave/security-advisories` package comes from the `Php Inspections (EA Extended)` plugin.

But nevertheless I also think that the warning for this specific package should be removed (or make it a weak warning - or make it configurable).

**Comment by acelaya** [comment]
Oops. My mistake then 😅
Thanks!


--
Alejandro Celaya Alastrué

**Comment by kalessil** [comment]
`roave/security-advisories` is just json-manifest, so IMO the warning about master-branches usages should not fire on the `roave/security-advisories` package.

**Comment by psliwa** [comment]
Will be added in the next version - sorry for late fix ;)
