### ISSUE TITLE
Thank you for this plugin

### ISSUE THREAD

**Issue by Ayesh** [psliwa/idea-composer-plugin#53]
Hi Piotr,
I couldn't find you anywhere to send this message, so I wrote this (closed) issue in the plugin issue tracker. 

Editing `composer.json` files is 100 times better thanks for this plugin, and I always feel confident I'm typing the correct schema. directives, license names, PSR-0/4 patterns, package versions, etc couldn't be made more easier thanks to this plugin. 

I wanted to say that, and I'm sure others agree too, that this plugin is super awesome and I couldn't help myself but write this after reading release notes of the latest update. It is so awesome what you are doing with the $1 pledge for every GH star and JB plugin rating. I also noted that you are from the lovely city Krakow is. I was so fortunate to have made there for a couple days. I owe you Wuzetka, Pierogi, and a Browar Zywiec the next time in Krakow (and of course Zakopane).

Merry Christmas!

**Comment by psliwa** [comment]
Thank you for good words. The plugin is not a rocket science, but probably it is useful. I wrote it when I was PHP developer and had bad experience with changing `composer.json` file (I always needed to use documentation and this was annoying :P).
