### ISSUE TITLE
How can I pass parameters to composer

### ISSUE THREAD

**Issue by SyuTingSong** [psliwa/idea-composer-plugin#54]
I am using develop server with whole php extensions while only a few extensions installed on my PC. I want to pass option `--ignore-platform-reqs` to the composer when updating and installing. I tried to write the such option in composer command but it reports that "Executable 'composer --ignore-platform-reqs' was not found in $PATH".

How can I pass parameters to composer?

**Comment by psliwa** [comment]
Hi,
I don't fully understand: are you asking about how to add such option to composer.json plugin configuration and use this option eg. while packages installation triggered by the plugin?

**Comment by SyuTingSong** [comment]
Yes, I want to get somewhere to set some options that can be passed to the composer command when installing and updating dependencies with the plugin.

**Comment by psliwa** [comment]
It will be available in the next release.  There is new `"composer update" options` tab in the plugin configuration.
