### ISSUE TITLE
PSR namespace completion should automatically append backslashes

### ISSUE THREAD

**Issue by axelcostaspena** [psliwa/idea-composer-plugin#56]
This is wrong: 
![image](https://user-images.githubusercontent.com/2345716/35268141-a06f5ea2-0028-11e8-90dd-6a5e30e4ea2c.png)

This is right:
![image](https://user-images.githubusercontent.com/2345716/35268103-858bdad4-0028-11e8-96ca-8367fe344198.png)

A

**Comment by psliwa** [comment]
Thanks. Done. Will be available in the next release.
