### ISSUE TITLE
Strange empty Annotator errors in Inspection window

### ISSUE THREAD

**Issue by Rarst** [psliwa/idea-composer-plugin#57]
When running bulk inspection with the plugin enabled there are strange empty Annotator errors detected for `composer.json` requires. There are no errors or warnings of any kind reported opening the file itself.

See screenshot:

![phpstorm-annotator-error](https://user-images.githubusercontent.com/737584/35556135-1f41cdd8-05aa-11e8-8f14-8a94c80b9b37.png)

**Comment by psliwa** [comment]
The same as https://github.com/psliwa/idea-composer-plugin/issues/83 - it has been already fixed.
