### ISSUE TITLE
Generic Java User-Agent

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [psliwa/idea-composer-plugin#58]
Your plugin uses a generic Java User-Agent ("Java/1.8.0_152-release" in my case) to request data from the composer repository (e. g. packagist.org). 

Could you please set an identifying user agent? Something like "idea-composer-plugin-x.y" so repostory hosters can identify which requests come from PHPStorm / IDEA and which requests come from other (malicious?) sources.

Thanks!

**Comment by psliwa** [comment]
Thanks. Done, it will be released in the next version.

**Comment by MatthiasKuehneEllerhold** [comment]
Thanks! Looking forward to it!
