### ISSUE TITLE
Add support of shift+f1 for navigating to package on packagist

### ISSUE THREAD

**Issue by Koc** [psliwa/idea-composer-plugin#6]

**Comment by psliwa** [comment]
:+1:

**Comment by kikuyu1** [comment]
That would awesome

**Comment by psliwa** [comment]
This feature will be in next release. There will be also quick docs (`ctrl+q`) and external docs (`shift+f1`)  for properties in composer.json.

**Comment by Koc** [comment]
Quick docs says "No documentation found."

**Comment by psliwa** [comment]
For packages there are only external docs (`shiflt+f1`). Quick docs are only for properties, for example when you move your caret to "authors" property, there should be quick docs (and also external docs - composer documentation site).
