### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by mbicknese** [psliwa/idea-composer-plugin#60]
Seeing PhpStorm allows you to configure a remote interpreter, it would be nice if that interpreter could be used for composer as well. Or maybe out of the box support for the official [Docker image](https://hub.docker.com/_/composer/).

At the moment I either get the following message. `composer` works in my terminal because I've set up an alias to run it in Docker. When using the `'composer' executable` option.
![image](https://user-images.githubusercontent.com/5147934/37388875-6bd5f9b0-2762-11e8-8727-ca227525af39.png)

Or (this might be an easy solution), when using the `composer.phar` option.
![image](https://user-images.githubusercontent.com/5147934/37388902-8c2f82da-2762-11e8-866e-a1ef4174588b.png)
In this case the interpreter is fully setup and works for other parts of the IDE like running unit tests.

**Comment by ktomk** [comment]
No, it does not work fully. Try with scratch files.

Have you tried instead of an alias to create an actual `composer`  command  that fire's up the docker'ed composer (which then also needs mappings, but I guess you have considered what you ask for)?

**Comment by psliwa** [comment]
Composer commands are supported only by PhpStorm's PHP Composer component, not by this plugin. Even if this plugin executes composer commands it uses PhpStorm build-in features.
