### ISSUE TITLE
Composer license not understood by PhpStorm as an array

### ISSUE THREAD

**Issue by Jamesking56** [psliwa/idea-composer-plugin#65]
If you specify the `license` key in `composer.json` as an array, Phpstorm thinks that you haven't specified the key at all and shows a tooltip warming:

`No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.`

Composer states that you can set the `license` key as an array: https://getcomposer.org/doc/04-schema.md#license

**Comment by voku** [comment]
only for reference -> https://youtrack.jetbrains.com/issue/WI-44569

**Comment by psliwa** [comment]
It will be fixed in the new version - sorry for late response ;)
