### ISSUE TITLE
Undefined order for excludedPackages in composerJson.xml

### ISSUE THREAD

**Issue by Blackskyliner** [psliwa/idea-composer-plugin#66]
**Context:**

I have the following file, created by this package I guess?

composeJson.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ComposerJsonPluginSettings">
    <unboundedVersionInspectionSettings>
      <excludedPackages>
        <pattern pattern="roave/security-advisories" />
        <pattern pattern="symfony/*" />
      </excludedPackages>
    </unboundedVersionInspectionSettings>
    <customRepositories />
    <composerUpdateOptions />
  </component>
</project>
```

**Problem:** Every now and then, I guess after indexing, the patterns within excludedPackages change their order. This leads to unnecessary changes in that file if .idea files are checked in.

**Solution:** Order the excludedPackages by pattern before/while writing them into the xml.

**Comment by Blackskyliner** [comment]
In theory it should be enough to swap the Set into a SortedSet at this line https://github.com/psliwa/idea-composer-plugin/blob/6c0f0213ea1b22b3d8885807d59e767233e1304c/src/main/scala/org/psliwa/idea/composerJson/settings/ProjectSettings.scala#L135

The `toList.asJava` later on should retain the sorting from the `SortedSet`.

**Comment by psliwa** [comment]
Will be fixed in the new release.
