### ISSUE TITLE
Incorrectly 'not installed' warning with packages replaced by other packages

### ISSUE THREAD

**Issue by crhg** [psliwa/idea-composer-plugin#67]
I put it in the composer.json file as follows and execute `composer install`.

```composer.json
{
    "require": {
        "illuminate/support": "^5.7"
    },
    "require-dev": {
        "orchestra/testbench": "^3.7"
    }
}
```

Installation was successful, but warning is issued that `illuminate/support` is not installed.

I looked into the situation and found out the following things.

* `illuminate/support` package is not installed.
* Instead, `laravel/framework` package is installed and it replaces `illumiate/support`. (It was installed with `orchestra/testbench` dependencies)

I think that 'not installed' warning should not be given under such circumstances.

**Comment by psliwa** [comment]
Will be fixed in a next release.
