### ISSUE TITLE
Should not warn ext-json isn't in composer.json for PHP > 5.2

### ISSUE THREAD

**Issue by SlyDave** [psliwa/idea-composer-plugin#70]
What steps will reproduce the problem?
1. Set PHP Version to anything > 5.2
2. composer init
3. Create PHP File, add $j = json_encode([]);
4. The inspector will report that ext-json is not included in composer.json

What is the expected result?

No warning about ext-json, As of PHP 5.2.0, the JSON extension is bundled and compiled into PHP by default.

What happens instead?
![image](https://user-images.githubusercontent.com/1842611/50220495-5e102f80-038a-11e9-8d37-8aad965fd8db.png)

**Comment by psliwa** [comment]
Hi, the same as here: https://github.com/psliwa/idea-composer-plugin/issues/73. This feature is not provided by this plugin.
