### ISSUE TITLE
list.json file is requested on non-packagist.org repositories

### ISSUE THREAD

**Issue by naderman** [psliwa/idea-composer-plugin#71]
The list.json file exists only on packagist.org not on other private repositories like Private Packagist or Satis. But I see requests for this file in our Private Packagist logs sent from your plugin.

**Comment by psliwa** [comment]
For custom repositories I changed the order for repo type checks:
-  check if it is private packagist - if yes, don't even try to send any request, just ignore this repo (private packagist is not supported right now anyway, so now it is explicitly covered in the code)
- assume satis repo and try to get data from it. If something fails go to the next check.
- assume packagist.org repo and try to get list.json
- if all checks failed then repo is just ignored

The fix will be available in the next release.

**Comment by naderman** [comment]
Why is Private Packagist not supported if satis is supported? They're both just private Composer repositories, you can treat them in the same way?

**Comment by psliwa** [comment]
Private Packagist needs authorization, satis not. Integration with Private Packagist has never worked because custom repositories feature from this plugin is older than Private Packagist - so authorization hasn't been implemented.

**Comment by naderman** [comment]
Satis may very well require authorization too. Actually most satis installations I know require http auth? So you're just saying auth is generally not supported? That seems like quite the limitation that would be easy to fix?

**Comment by psliwa** [comment]
Yes, auth is not supported. Yes, it is limitation. I will think about fixing this. Such feature doesn't look simple. Http requests are not done via `composer` command, so I cannot use `composer` here and delegate everything to external command or built-in PhpStorm features. I can see in composer documentation that credentials are stored in `auth.json` file but I am not sure if third party plugin should read such sensitive information because of security.

**Comment by naderman** [comment]
I'd say if your connecting to repositories based on the composer.json, you should also follow the Composer way of specifying authentication. So I think it would be fine for your plugin to read this information as long as it only uses it to connect to the respective repositories in the same way as Composer. Composer will first load $COMPOSER_HOME/auth.json (typically ~/.composer/auth.json on *nix, some local user dir on windows, i think the composer docs clarify this), then any auth.json file in the same directory as composer.json. Although technically auth can also be specified in the same way in a "config" key inside composer.json or in $COMPOSER_HOME/config.json, this is discouraged and I think if you just implement the standard auth.json support with the two file locations, that would probably be enough for most people.

I'd be happy to review and help you test your solution! :-)

**Comment by psliwa** [comment]
I created issue for that: https://github.com/psliwa/idea-composer-plugin/issues/86. I am not sure when I start implementing this feature because I have few outstanding things in backlog and also very limited time.

Thanks and regards.
