### ISSUE TITLE
Do not request provider files for platform packages without slash in the name

### ISSUE THREAD

**Issue by naderman** [psliwa/idea-composer-plugin#72]
Packages like PHP extensions (ext-foo) or the internal Composer plugin API (composer-plugin-api) do not have a vendor prefix with a slash. You should not be making requests to repository URLs for these packages. I see requests for /org-name/p/composer-plugin-api.json on Private Packagist sent by this plugin.

**Comment by psliwa** [comment]
Fixed - will be available in the next release.
