### ISSUE TITLE
Should not warn ext-zip isn't in composer.json for PHP > 5.3

### ISSUE THREAD

**Issue by SlyDave** [psliwa/idea-composer-plugin#73]
What steps will reproduce the problem?

Set PHP Version to anything > 5.3
composer init
Create PHP File, add $z = new \ZipArchive();
The inspector will report that ext-zip is not included in composer.json
What is the expected result?

No warning about ext-zip, As of PHP 5.3 this extension is built-in. (http://php.net/manual/en/zip.installation.php)

What happens instead?
![image](https://user-images.githubusercontent.com/1842611/51127787-48bde200-181e-11e9-8962-7247db23353f.png)

**Comment by psliwa** [comment]
Hi, this feature is provided by PhpStorm - not by this plugin.
