### ISSUE TITLE
Rejecting Dialog 'Untrusted Server's Certificate' does not reject

### ISSUE THREAD

**Issue by staabm** [psliwa/idea-composer-plugin#76]
we work with a satis instance which uses a self-signed https certificate. it seems that while editing the composer.json file with this plugin installed, it tries to fetch some http(s) resources.

a dialog popups up, which requries a "confirm" or "reject". the modal dialog seems somehow frozen and I can neither close the dialog with one of these buttons.
effectively phpstorm is getting unusable with this dialog open, because it is modal and cannot be closed.

see related issue https://youtrack.jetbrains.com/issue/WI-27147

**Comment by Jean85** [comment]
I'm having the same issue, but I'm not sure is related to this plugin, because I got the same alert on different certificates, that should be called by different plugins (or even the plain IDE).

I fear the root issue is in the CA bundle inside the IDE's Java stuff.

**Comment by psliwa** [comment]
What PhpStorm / IntelliJ version do you use? I tested under provided configuration and sample code and I was able to accept / reject a certificate.

```
IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
```

and repository with self-sign certificate:

```json
    "repositories": [
        {
            "url": "https://self-signed.badssl.com/",
            "type": "composer"
        }
    ]
```

**Comment by Jean85** [comment]
I discovered that the root issue was a custom VM option in my IDE: years ago I was using the Oracle JDK package, and the setting was pointing to the CA Bundle of that package, that is now outdated.

Hence, PHPStorm was struggling in recognizing all newer certificates as valid; i.e., Packagists uses Let's Encrypt, so it's renewed recently.

Removing that custom VM option fixed it for me!

**Comment by staabm** [comment]
The only way for me to resolve this problem was un-instaling the plugin

**Comment by psliwa** [comment]
I don't have enough information in order to reproduce the issue. If you are able to provide more info, (eg. `Help > Collect Troubleshooting Information`, what and how exactly you are editing) let's re-open the issue.
