### ISSUE TITLE
Mark the plugin as compatible only with PhpStorm and IntelliJ IDEA Ultimate

### ISSUE THREAD

**Issue by dlsniper** [psliwa/idea-composer-plugin#77]
Hello,

First of all, thank you for the plugin.
Second, could you please take a moment and mark the plugin as compatible only with IntelliJ IDEA Ultimate and PhpStorm, since those are the only two IDEs which support PHP?
Please let me know if you need any help.
Thank you.

**Comment by psliwa** [comment]
Hi. Yes, sure - I will do that soon. Thanks.

**Comment by psliwa** [comment]
Done.
