### ISSUE TITLE
Should not warn if dependency is listed as a suggested package

### ISSUE THREAD

**Issue by tored** [psliwa/idea-composer-plugin#82]
If a dependency is listed in `suggest` property for `composer.json` it should no longer warn that it is missing in `composer.json`

Example, if library is using an interface for database abstraction, one implementation could be for PDO another for mysqli and it it up the user of the library to pick one. `suggest` would then be

```
"suggest": {
        "ext-pdo": "For PdoDb class",
        "ext-mysqli": "For MysqliDb class"
}
```

**Comment by psliwa** [comment]
Hi, thanks for reporting. I am not sure where is the issue or if the issue is in the plugin or built-in composer support in Php Storm itself. Can you show me eg. screenshot?
