### ISSUE TITLE
Inspection indications "12 information", but none shown

### ISSUE THREAD

**Issue by laurin1** [psliwa/idea-composer-plugin#83]
With the plugin installed, this Inspection indicator shows up and says 12 Information items, but that's it:

![image](https://user-images.githubusercontent.com/75857/63437814-e69b1000-c3f0-11e9-8d6b-74171d7fb046.png)

**Comment by psliwa** [comment]
Thanks for reporting - fixed in the new version of the plugin (`1.0.30`).
