### ISSUE TITLE
Install all not installed packages doesn't work with vagrant / remote interpreter

### ISSUE THREAD

**Issue by wernerkrauss** [psliwa/idea-composer-plugin#84]
I installed vagrant and configured PHPStorm / Idea to use the remote PHP interpreter in my vagrant box. I can run remote php scripts, use composer install, update etc... but for some reason the command "Install all not installed packages" doesn't work.

It also doesn't show any errors, it just fails silently.

Using the built in update command works.

Could you please have a look into it or clarify, that your plugin / that functionality doesn't work with remote interpreters? If not, it might be useful to disable this shortcode.

Thanks for providing a useful composer plugin!

**Comment by psliwa** [comment]
Thanks. It should be working now since `1.0.31` version.

**Comment by wernerkrauss** [comment]
Thanks, I can confirm it now works!
