### ISSUE TITLE
vendor/bin scripts not recognized as valid scripts

### ISSUE THREAD

**Issue by InvisibleSmiley** [psliwa/idea-composer-plugin#89]
Scripts referring to vendor/bin scripts are not recognized as valid scripts, e.g. `"cs-check": "phpcs"`.

Current behavior:
- `class 'phpcs' does not exist.`
- `Method is empty.`

Documented here: https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands

This is widely used, e.g. see https://github.com/zendframework/zend-expressive-skeleton/blob/master/composer.json#L103

**Comment by psliwa** [comment]
Thanks, I fixed this inspection and added support for `vendor/bin` scripts suggestions and references.
