### ISSUE TITLE
Plugin Error: Plugin "PHP composer.json support" is incompatible (marked as broken).

### ISSUE THREAD

**Issue by SHSharkar** [psliwa/idea-composer-plugin#92]
```
Plugin Error: Plugin "PHP composer.json support" is incompatible (marked as broken).
```

```
PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2474M
Cores: 24
Registry: run.processes.with.pty=TRUE
```

**Comment by psliwa** [comment]
Duplicate: https://github.com/psliwa/idea-composer-plugin/issues/91. When you update the plugin to `1.0.38` version its features will be effectively disabled and you will see farewell notification.

**Comment by auipga** [comment]
It doesn't show up in the list of installed plugins.
It can't be updated from within PhpStorm (2020.1) so your advise isn't applicable.

My solution was to `rm -r -i ~/.local/share/JetBrains/PhpStorm2020.1/ideaComposerPlugin`.
Source: https://github.com/psliwa/idea-composer-plugin/issues/91#issuecomment-583396685
For non-linux paths see https://www.jetbrains.com/help/idea/tuning-the-ide.html#plugins-directory and remove the plugin directory accordingly.

You may add this to the README.md

**Comment by danielkurecka** [comment]
For those that use JetBrains Toolbox App, the path to ideaComposerPlugin directory is different:

~/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/`<build-number>`.plugins/ideaComposerPlugin
